export enum Fonts {
  none = '',
  montserrat64medium = 'normal normal 500 4rem \'Montserrat\', sans-serif',
  montserrat48medium = 'normal normal 500 3rem \'Montserrat\', sans-serif',
  montserrat36medium = 'normal normal 500 2.25rem \'Montserrat\', sans-serif',
  montserrat24bold = 'normal normal 700 1.5rem \'Montserrat\', sans-serif',
  montserrat24regular = 'normal normal 400 1.5rem \'Montserrat\', sans-serif',
  montserrat16bold = 'normal normal 700 1rem \'Montserrat\', sans-serif',
  montserrat16regular = 'normal normal 400 1rem \'Montserrat\', sans-serif',
  montserrat11bold = 'normal normal 700 0.688rem \'Montserrat\', sans-serif',
  montserrat11regular = 'normal normal 400 0.688rem \'Montserrat\', sans-serif',
  montserrat8bold = 'normal normal 700 0.5rem \'Montserrat\', sans-serif',
  federant48regular = 'normal normal 400 3rem \'Federant\', sans-serif',
  federant24regular = 'normal normal 400 1.5rem \'Federant\', sans-serif',
}
