export enum Warnings {
  'NEED_TO_LOGIN' = 'warnings.NEED_TO_LOGIN',
  'CANNOT_OWN_MORE' = 'warnings.CANNOT_OWN_MORE',
  'ALREADY_MAX_QUANTITY_OWNED' = 'warnings.ALREADY_MAX_QUANTITY_OWNED',
  'CANNOT_OWN_MORE_WHEN_NOT_QUANTITY_BOUGHT' = 'warnings.CANNOT_OWN_MORE_WHEN_NOT_QUANTITY_BOUGHT',
}
